// LOCAL DEVELOPMENT ONLY - This file is NOT committed to git
// In production, this file is generated by GitHub Actions using repository Secrets
// See .github/workflows/deploy.yml
class ApiConfig {
  static const String geminiApiKey = String.fromEnvironment('GEMINI_API_KEY', defaultValue: '');
  static const String supabaseUrl = String.fromEnvironment('SUPABASE_URL', defaultValue: '');
  static const String supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY', defaultValue: '');
}
