class UserProfile {
  final String id;
  final String? email;
  final String? phone;
  final String? displayName;
  final String? avatarUrl;
  final DateTime? birthday;
  final List<String> tags; // e.g. ["Playa", "Bailar"]
  final bool isGuest;

  const UserProfile({
    required this.id,
    this.email,
    this.phone,
    this.displayName,
    this.avatarUrl,
    this.birthday,
    this.tags = const [],
    this.isGuest = false,
  });

  // Factory for creating a temporary guest user
  factory UserProfile.guest({required String name}) {
    // In a real app, ID would be generated by UUID
    return UserProfile(
      id: "temp_guest_${DateTime.now().millisecondsSinceEpoch}",
      displayName: name,
      isGuest: true,
      tags: [],
    );
  }

  // To/From JSON methods will be added here for serialization
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'phone': phone,
      'display_name': displayName,
      'avatar_url': avatarUrl,
      'birthday': birthday?.toIso8601String(),
      'tags': tags,
      'is_guest': isGuest,
    };
  }

  factory UserProfile.fromJson(Map<String, dynamic> map) {
    return UserProfile(
      id: map['id'] as String,
      email: map['email'] as String?,
      phone: map['phone'] as String?,
      displayName: map['display_name'] as String?,
      avatarUrl: map['avatar_url'] as String?,
      birthday: map['birthday'] != null ? DateTime.parse(map['birthday']) : null,
      tags: List<String>.from(map['tags'] ?? []),
      isGuest: map['is_guest'] ?? false,
    );
  }
}
