-- =============================================================================
-- MIGRATION: Auto-Create User Profiles
-- Description: Creates a trigger that automatically inserts a row into public.profiles
-- whenever a new user registers through Supabase Auth.
-- Fixes: "Key is not present in table profiles" error during early voting.
-- =============================================================================

-- 1. Create the Function Handler
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- We use the ID generated by Supabase Auth (auth.users)
  -- The full_name can be extracted from metadata if they registered via Google/Phone
  -- If not, it falls back to parsing their email prefix or a generic string.
  INSERT INTO public.profiles (id, full_name, display_name, avatar_url, updated_at)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', SPLIT_PART(NEW.email, '@', 1), 'Nuevo Usuario'),
    COALESCE(NEW.raw_user_meta_data->>'display_name', SPLIT_PART(NEW.email, '@', 1), 'Nuevo Usuario'),
    NEW.raw_user_meta_data->>'avatar_url',
    now()
  )
  ON CONFLICT (id) DO NOTHING; -- Gracefully handle if they somehow already have one
  
  RETURN NEW;
END;
$$;

-- 2. Bind the Trigger to auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 3. (Optional Retro-Fix) Backfill existing auth.users who lack a profile
INSERT INTO public.profiles (id, full_name, display_name, updated_at)
SELECT 
  id, 
  COALESCE(raw_user_meta_data->>'full_name', SPLIT_PART(email, '@', 1), 'Usuario Antiguo'), 
  COALESCE(raw_user_meta_data->>'display_name', SPLIT_PART(email, '@', 1), 'Usuario Antiguo'), 
  now()
FROM auth.users
WHERE id NOT IN (SELECT id FROM public.profiles)
ON CONFLICT (id) DO NOTHING;
