import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:planmapp/features/itinerary/domain/models/activity.dart';

class ItineraryService {
  final SupabaseClient _supabase = Supabase.instance.client;

  Future<List<Activity>> getActivities(String planId) async {
    try {
      final response = await _supabase
          .from('activities')
          .select()
          .eq('plan_id', planId)
          .order('start_time', ascending: true);

      return (response as List).map((e) => Activity.fromJson(e)).toList();
    } catch (e) {
      throw Exception('Error loading itinerary: $e');
    }
  }

  Future<void> createActivity(Activity activity) async {
    try {
      final user = _supabase.auth.currentUser;
      if (user == null) throw Exception("User not authenticated");

      // Note: we don't send 'id' or 'created_at' as they are generated by DB
      await _supabase.from('activities').insert({
        ...activity.toJson(),
        'created_by': user.id,
      });
    } catch (e) {
      throw Exception('Error creating activity: $e');
    }
  }

  Future<void> deleteActivity(String activityId) async {
      try {
          await _supabase.from('activities').delete().eq('id', activityId);
      } catch (e) {
          throw Exception('Error deleting activity: $e');
      }
  }
}
