name: daily-scrape-offers
on:
  schedule:
    - cron: "0 10 * * *" # Se ejecuta a las 5:00 AM hora Colombia
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        # Aquí añadimos "scripts/" porque ahí está tu archivo
        run: pip install -r scripts/requirements.txt
      
      - name: Run scripts/scrape_events.py
        # Aquí también añadimos "scripts/" para que encuentre el script
        run: python scripts/scrape_events.py

      - name: Save Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Nuevas ofertas y eventos detectados" || exit 0
          git push
