name: Deploy Planmapp
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Paso para crear el archivo que le falta a tu backup
      - name: Create API Config
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          mkdir -p lib/core/config
          cat > lib/core/config/api_config.dart << EOF
          class ApiConfig {
            static const String geminiApiKey = '${GEMINI_KEY}';
            static const String supabaseUrl = '${SUPABASE_URL}';
            static const String supabaseAnonKey = '${SUPABASE_ANON_KEY}';
          }
          EOF

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
