name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Supabase Functions
        run: |
          # Solo ejecutará el comando si se proporcionaron los permisos
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "ERROR: SUPABASE_ACCESS_TOKEN is required in Github Secrets."
            exit 1
          fi
          
          if [ -z "$PROJECT_ID" ]; then
            echo "ERROR: SUPABASE_PROJECT_ID is required in Github Secrets."
            exit 1
          fi
          
          supabase functions deploy fcm-dispatcher --project-ref $PROJECT_ID
          supabase functions deploy notify-debts --no-verify-jwt --project-ref $PROJECT_ID
